#!/bin/sh


function die
{
	echo "$(basename $0): $*" >&2
	exit 1
}

print_revs()
{
while read oldrev newrev refname; do
	echo "$newrev"
done
}

GIT_DIR=$(cd $GIT_DIR; pwd -P)


newrev=$(print_revs | tail -1)
curl -X POST "http://localhost:8080/git/commit/$newrev" || die "web service call failed"

# Reject the commit to prevent users from altering the git repo.
exit 1
